### PR TITLE
Fix omemo, after forking

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by genofire** [comment]
It has to be this value, take a look at this XEP:
https://xmpp.org/extensions/xep-0384.html

**Comment by ReyKoxha** [comment]
Thanks a lot for pointing this out.

Interestingly OMEMO works just fine, yet I have to follow the XEP. Especially considering that someone wants to fork this repo.

**Comment by genofire** [comment]
Between your clients it should works, but not with other clients ...

**Comment by ReyKoxha** [comment]
Undone in abfd9d3

**Comment by genofire** [comment]
So you did not want to be compatible wit other clients?

**Comment by ReyKoxha** [comment]
Hey genofire,

I saw that there was lots of mock from C people about this project.
They think that my target is to steal users from C or even open up a business as they call it (they most likely think I want to make money or even "sell" this as it would be "mine").

While I definitely want to gain users, I am not looking for any kind of competition with other clients.
As stated in the README (just updated it) the users I am looking for are newbies who have not the slightest clue about setting up/finding a XMPP server.

My target on the long run is to raise their awarness about XMPP and its idea, driving them off to other clients and appropiate federation.

If you think that this is the wrong way -  I am open for all suggestions.

**Comment by genofire** [comment]
I really hate it that there is a xmpp client how breaks standards / XEPs - so that other clients like gajim, dino and Pix-Art are not able to chat omemo encrypted.
Please revert your revert.

---
Off Topic to business models:
- it is okay to fork a GPL application and publish it (earn money with it) if you publish your code.
  So it is legal
- i am happy about a fork which is free installable from PlayStore (which i not use) and could use other xmpp server - thats more open then conversations is.
  - so please do not cut off the support of federation like with this revert


So please ignore the Conversations people and keep making this step forward to a more open xmpp client.

Another step forward to be more open the Conversations would be:
It would be glade to see a gui like [Pix-Art](https://raw.githubusercontent.com/kriztan/Pix-Art-Messenger/master/metadata/en-US/phoneScreenshots/01.jpg), which show a list of provided servers.
By discovery the servers on the [compliance.conversations.im](https://compliance.conversations.im/) and there API [api/compliant_servers](https://compliance.conversations.im/api/compliant_servers/)

**Pull request merged**
